### ISSUE TITLE
Script fails with "parsing error"

### ISSUE THREAD

**Issue by bauerj** [hannob/jitsivuln#1]
For example:

```
~ ./jitsivuln meet.meerfarbig.net
https://meet.meerfarbig.net/http-bind parsing error
```

Adding a `traceback.print_exc()` shows that it fails at `serverfirstmessage = base64.b64decode(xml1.getElementsByTagName('challenge')[0].firstChild.nodeValue).decode()`.  The response at that point is `<body type='terminate' condition='item-not-found' xmlns='http://jabber.org/protocol/httpbind'/>`.

Does that mean this server is not vulnerable? If so, the script should indicate that in a more understandable way.

**Comment by hannob** [comment]
TBH I don't know what exactly that means. Maybe the server has been reconfigured to not expose certain functionality on BOSH?
Is that your server?

**Comment by bauerj** [comment]
>  Is that your server?

No, it's not. I got it from the list of [public instances](https://github.com/jitsi/jitsi-meet/wiki/Jitsi-Meet-Instances). Testing with some other random servers from there (e.g. meet.lrz.de) yields the same result.

**Comment by patrickhanft** [comment]
I was trying the script on `konferenz.netzbegruenung.de` which is operated by Netzbegruenung e.V. with whom I'm associated. I also get this error message due to `<body type='terminate' condition='item-not-found' xmlns='http://jabber.org/protocol/httpbind'/>` response.

I will ask the guys who did the jitsi setup, how they did it, but I just assume there was principally no docker involved.

**Comment by fzechert** [comment]
I can confirm this problem with same error message and same response on my own jitsi server.

**Comment by hannob** [comment]
So to be clear, my best guess is that these are simply not vulnerbale because they don't allow login. But not 100% sure, maybe needs more analysis. @fzechert do you use the docker installation method?

**Comment by fzechert** [comment]
No I installed it on a ubuntu server from the available deb packages.

**Comment by hannob** [comment]
So based on what I heard the most likely reason for these errors is that the server has been installed without docker, which probably doesn't expose the bosh functions. I will add a "probably not vulnerable" note.

**Comment by rugk** [comment]
It even happens for the main instance…

```shell
$ python3 -V
Python 3.7.6
$ python -V 
Python 3.7.6
§ ./jisti.py meet.jit.si                 
https://meet.jit.si/http-bind parsing error, probably not vulnerable
$ ./jisti.py meet.golem.de # but not for this ok
https://meet.golem.de/http-bind not vulnerable
```

Fedora 31 

---

BTW, I don't get why you've closed this issue, in the latest master the issue is still not fixed.

**Comment by hannob** [comment]
What do you expect as a fix?
This error basically means there's something happening during the login that is not as expected.
This seems to happen if you don't use the docker installation, probably the BOSH interface doesn't expose anything there. So in essence you're scanning a system that is not running the thing that you want to check for the vulnerability, so errors happen. That's expected. Run it with "-q" and it'll be silent for anything except finding the vuln.

**Comment by rubo77** [comment]
Same Problem here with a version installed by this instruction:
https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md

But good point. maybe it doesn't need a fix
